### ISSUE TITLE
Document the current process completed in Readme file with detailed description. 

### ISSUE THREAD

**Issue by Gagan-Dheep** [Srivatsajbhat/RepIt#1]
Start Documentation.

**Comment by saikumarseepana** [comment]
hey @Gagan-Dheep can you assign this issue to me.

**Comment by Shubham1450** [comment]
I want to work on this issue can you please assign it to me. @Gagan-Dheep

**Comment by AtulPatidar1709** [comment]
hello Sir I want to work on this issue and also wants to get all the information relates to that. @Gagan-Dheep

**Comment by Srivatsajbhat** [comment]
Done with the issue
